---

- name: Importar playbooks
  hosts: localhost
- name: Configuracion de firewall en CentOS
  ansible.builtin.import_playbook: security_centos.yml
- name: Configuracion de firewall en ubuntu
  ansible.builtin.import_playbook: security_ubuntu.yml
- name: Configuracion de WebApp
  ansible.builtin.import_playbook: web.yml
- name: Configuracion de database
  ansible.builtin.import_playbook: database.yml