---

- name: Crear la Base de datos ToDo
  hosts: database
  become: true
  user: sysadmin

  tasks:

  - name: Crear base de datos todo
    community.mysql.mysql_db:
      name: todo
      state: present
      login_user: root
      login_password: dbroot

  - name: Crear tablas en la base de datos todo
    community.mysql.mysql_query:
      query: |
          CREATE TABLE IF NOT EXISTS `users` (
            `id` int(3) NOT NULL AUTO_INCREMENT,
            `first_name` varchar(20) DEFAULT NULL,
            `last_name` varchar(20) DEFAULT NULL,
            `username` varchar(250) DEFAULT NULL,
            `password` varchar(20) DEFAULT NULL,
            PRIMARY KEY (`id`)
          ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

          CREATE TABLE IF NOT EXISTS `todos` (
            `id` bigint(20) NOT NULL AUTO_INCREMENT,
            `description` varchar(255) DEFAULT NULL,
            `is_done` bit(1) NOT NULL,
            `target_date` datetime(6) DEFAULT NULL,
            `username` varchar(255) DEFAULT NULL,
            `title` varchar(255) DEFAULT NULL,
            PRIMARY KEY (`id`)
          ) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4
          COLLATE=utf8mb4_general_ci;
      login_db: todo
      login_user: root
      login_password: dbroot

  - name: Crear usuario y conceder permisos en la base de datos todo
    community.mysql.mysql_user:
      name: todo
      password: prueba2024
      priv: "todo.*:ALL"
      state: present
      login_user: root
      login_password: dbroot
      host: '%'
      update_password: always