---

- name: Se crea el servicio Tomcat
  hosts: webapp
  become: true
  user: sysadmin

  tasks:

  - name: Crear usuario Tomcat
    ansible.builtin.user:
      name: tomcat
      group: tomcat
      shell: /sbin/nologin
      state: present

  - name: Crear Grupo Tomcat
    ansible.builtin.group:
      name: tomcat
      state: present

  - name: Se configura los permisos y dueños del directorio Tomcat
    ansible.builtin.file:
      path: /opt/tomcat
      owner: tomcat
      group: tomcat
      mode: '0755'
      recurse: true
      state: directory

  - name: Copiar archivo tomcat.service
    ansible.builtin.copy:
      src: ./files/tomcat.service
      dest: /etc/systemd/system/tomcat.service
      owner: root
      group: root
      mode: '0644'

  - name: Recargar los servicios
    ansible.builtin.command: systemctl daemon-reload

  - name: Habilitar servicio Tomcat
    ansible.builtin.systemd_service:
      name: tomcat
      enabled: true

  - name: Prender el servico Tomcat
    ansible.builtin.systemd_service:
      name: tomcat
      state: started