---

- name: Se instala tomcat apache y la aplicacion web
  hosts: webapp
  become: yes
  user: sysadmin

  tasks:

  - name: Instalar de Java 11
    ansible.builtin.dnf:
      name: java-11-openjdk
      state: installed
    
  - name: Descargar Tomcat
    ansible.builtin.get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.100/bin/apache-tomcat-8.5.100.tar.gz
      dest: /tmp/apache-tomcat-8.5.100.tar.gz

  - name: Descomprimir Tomcat
    ansible.builtin.unarchive:
      src: /tmp/apache-tomcat-8.5.100.tar.gz
      dest: /opt/
      remote_src: yes

  - name: Crear enlace simbólico para Tomcat
    ansible.builtin.file:
      src: /opt/apache-tomcat-8.5.100.tar.gz
      dest: /opt/tomcat
      state: link

  - name: Copiar de archivo todo.war
    ansible.builtin.copy:
      src: /config/todo.war
      dest: /opt/tomcat/webapps/

  - name: Crear directorio para configuracion de base de datos
    ansible.builtin.file:
      path: /opt/config
      state: directory
      mode: '0755'

  - name: copiar de archivo app.properties
    ansible.builtin.copy:
      src: /config/app.properties
      dest: /opt/config/

  - name: Create Tomcat group
    group:
      name: tomcat
      state: present

  - name: Create Tomcat user
    user:
      name: tomcat
      group: tomcat
      shell: /sbin/nologin
      state: present

  - name: Copy Tomcat service file
    copy:
      src: /config/tomcat.service
      dest: /etc/systemd/system/tomcat.service
      owner: root
      group: root
      mode: '0644'

  - name: Reload systemd to pick up new service
    command: systemctl daemon-reload

  - name: Enable Tomcat service
    systemd:
      name: tomcat
      enabled: yes

  - name: Start Tomcat service
    systemd:
      name: tomcat
      state: started